name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run

      - name: Check files content s
        uses: cypress-io/github-action@v5
        with:
          command: ls -a
          

          
          
          
