name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Run tests then artifact the test results
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout - Clone the repository master branch
        uses: actions/checkout@v3

      - name: Run the testcases
        uses: cypress-io/github-action@v5
        with:
            command: cypress run --record --group 4x-electron --parallel
#           command: npx cypress run --record --group 2x-chrome --key dbea81c2-9e90-440e-9ee1-25c40030a1c5 --parallel

      - name: upload test results report as artifact in the ci pipeline
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: ./cypress/reports/html
